/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
/*
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
//const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
//  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
/*  Sidebar: [
    'index',
    {
      type: 'category',
      label: 'Resources',
      link: {
        type: 'generated-index',
      },
      collapsed: true,
      items: [
        'Maintainer'
      ]
    }
  ]

};

module.exports = sidebars;
*/
module.exports = {
  wiki: [
    'index',
    {
      type: 'category',
      label: 'Getting started',
      link: {type: 'doc', id: 'gettingstarted/makerpenmenu'},
      items: ['gettingstarted/syncedlocal']
    },
    {
      type: 'category',
      label: 'Value Types',
      link: {type: 'doc', id: 'gettingstarted/valuetypes'},
      items: [
        {
          type: 'doc',
          id: 'gettingstarted/valuetypes/exec', // document ID
          className: 'exec'
        },
        {
          type: 'doc',
          id: 'gettingstarted/valuetypes/bool', // document ID
          className: 'bool'
        },
        {
          type: 'doc',
          id: 'gettingstarted/valuetypes/float', // document ID
          className: 'float'
        },
        {
          type: 'doc',
          id: 'gettingstarted/valuetypes/int', // document ID
          className: 'int'
        },
        {
          type: 'doc',
          id: 'gettingstarted/valuetypes/player', // document ID
          className: 'player'
        },
        {
          type: 'doc',
          id: 'gettingstarted/valuetypes/recroomobject', // document ID
          className: 'recroomobject'
        },
        {
          type: 'doc',
          id: 'gettingstarted/valuetypes/vector3', // document ID
          className: 'vector3'
        },
        {
          type: 'doc',
          id: 'gettingstarted/valuetypes/string', // document ID
          className: 'string'
        },
          ]
    },
  ],
};